# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4529a0dc94d7123a3fe5896b24222d4"
name = "LIMITER Order Limits"
application_url = "https://rulelimit.magecomp.net"
embedded = true
handle = "limiter-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = [
  "https://rulelimit.magecomp.net/authenticate",
]

[app_proxy]
url = "https://rulelimit.magecomp.net/api/rulebase-proxy"
subpath = "rule-limit-proxy"
prefix = "a"

[pos]
embedded = false

[build]
include_config_on_deploy = true
