# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01fc63baa1b099847c49460e0fedb87b"
name = "limiter11"
application_url = "https://financial-latina-hundreds-analog.trycloudflare.com"
embedded = true
handle = "limiter11"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "https://everything-locate-tourist-steering.trycloudflare.com/webhook/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://everything-locate-tourist-steering.trycloudflare.com/webhook/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://everything-locate-tourist-steering.trycloudflare.com/webhook/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://financial-latina-hundreds-analog.trycloudflare.com/authenticate"
]

[app_proxy]
url = "https://financial-latina-hundreds-analog.trycloudflare.com/api/rulebase-proxy"
subpath = "rule-limit-proxy"
prefix = "a"

[pos]
embedded = false
